--------------------------------------------------------
--  Fichier créé - mardi-mars-08-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COMMANDE
--------------------------------------------------------

  CREATE TABLE "HIBAFF"."COMMANDE" 
   (	"ID_COM" NUMBER, 
	"DATE_RECEP" VARCHAR2(20 BYTE), 
	"DATE_LIVR" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into HIBAFF.COMMANDE
SET DEFINE OFF;
Insert into HIBAFF.COMMANDE (ID_COM,DATE_RECEP,DATE_LIVR) values ('1211','21/04/2022','22/04/2022');
Insert into HIBAFF.COMMANDE (ID_COM,DATE_RECEP,DATE_LIVR) values ('2122','21/02/2022','23/02/2022');
Insert into HIBAFF.COMMANDE (ID_COM,DATE_RECEP,DATE_LIVR) values ('707','21/12/2021','11/01/2022');
--------------------------------------------------------
--  DDL for Index COMMANDE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HIBAFF"."COMMANDE_PK" ON "HIBAFF"."COMMANDE" ("ID_COM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table COMMANDE
--------------------------------------------------------

  ALTER TABLE "HIBAFF"."COMMANDE" ADD CONSTRAINT "COMMANDE_PK" PRIMARY KEY ("ID_COM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HIBAFF"."COMMANDE" MODIFY ("ID_COM" NOT NULL ENABLE);
